### ISSUE TITLE
[ERROR] restarting 'ascii' codec can't encode character u'\u2640' in position 7: ordinal not in range(

### ISSUE THREAD

**Issue by IllidanU** [j-e-k/pgoapi#69]
2016-07-25 15:03:00,507 [   pokecli] [ INFO] Your given location: -
2016-07-25 15:03:00,509 [   pokecli] [ INFO] lat/long/alt: -
2016-07-25 15:03:00,519 [auth_google] [ INFO] Google login for:-
2016-07-25 15:03:01,204 [auth_google] [ INFO] Google Login successful.
2016-07-25 15:03:01,206 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
2016-07-25 15:03:01,334 [    pgoapi] [ INFO] Finished RPC login sequence (app simulation)
2016-07-25 15:03:01,338 [    pgoapi] [ INFO] Login process completed
2016-07-25 15:03:01,486 [    pgoapi] [ INFO] Username:-, Currencies: POKECOIN: -,STARDUST: -, Pokemon Caught in this run: 0
2016-07-25 15:03:01,753 [    pgoapi] [ INFO] Player Items: PokeBalls: -, GreatBalls: -, MasterBalls: -, UltraBalls: -
 Potion: -, Super Potion:-, Max Potion-, Hyper Potion -
2016-07-25 15:03:01,859 [    pgoapi] [ INFO] Username:-, Currencies: POKECOIN: -,STARDUST: -, Pokemon Caught in this run:-
2016-07-25 15:03:03,095 [    pgoapi] [ INFO] Walking to fort at  http://maps.google.com/maps-
2016-07-25 15:03:03,269 [    pgoapi] [ INFO] Username:-, Currencies: POKECOIN: -,STARDUST: -, Pokemon Caught in this run: -
2016-07-25 15:03:03,270 [    pgoapi] [ INFO] On my way to the next fort! :)
2016-07-25 15:03:04,776 [    pgoapi] [ INFO] No nearby pokemon
2016-07-25 15:03:04,867 [    pgoapi] [ INFO] Username: -, Currencies: POKECOIN: -,STARDUST: -, Pokemon Caught in this run: -
2016-07-25 15:03:04,868 [    pgoapi] [ INFO] On my way to the next fort! :)
2016-07-25 15:03:06,068 [    pgoapi] [ INFO] No nearby pokemon
2016-07-25 15:03:06,158 [    pgoapi] [ INFO] Username: -, Currencies: POKECOIN: -,STARDUST: -, Pokemon Caught in this run: -
2016-07-25 15:03:06,161 [    pgoapi] [ INFO] On my way to the next fort! :)
2016-07-25 15:03:07,346 [    pgoapi] [ INFO] No nearby pokemon
2016-07-25 15:03:10,484 [    pgoapi] [ INFO] Username: -, Currencies: POKECOIN: -,STARDUST: -, Pokemon Caught in this run: -
2016-07-25 15:03:10,500 [   pokecli] [ERROR] Error in main loop, restarting 'ascii' codec can't encode character u'\u2640' in position 7: ordinal not in range(128)

**Comment by IllidanU** [comment]
Config setting:
"MIN_KEEP_IV" : 83,
        "KEEP_CP_OVER": 500,
        "STEP_SIZE": 120,
        "EXPERIMENTAL": true,
        "SKIP_VISITED_FORT_DURATION": 600,
        "SPIN_ALL_FORTS": false
Error keeps happening no matter  "SPIN_ALL_FORTS" is true or false

**Comment by venounan** [comment]
2016-07-25 18:18:12,163 [   pokecli] [ERROR] Error in main loop, restarting 'ascii' codec can't encode character u'\u2642' in position 7: ordinal not in range(128)

I'm having the same issue

**Comment by j-e-k** [comment]
So wild hunch:

So U+2640 (u'\u2640') Is  ♀
Position 7 would correspond to the ♀ in nidoran♀

What version of python are you using and can you output the result of `pip freeze`

**Comment by joychugh** [comment]
I tried to do ascii encoding to stop that, could be python version.

**Comment by venounan** [comment]
I can't speak for the main guy, but I'm on 2.7 and pip freeze outputs 

`click==6.6
colorama==0.3.7
enum34==1.1.6
expiringdict==1.1.3
Flask==0.11.1
future==0.15.2
geopy==1.11.0
googlemaps==2.4.4
gpsoauth==0.3.0
haversine==0.4.5
itsdangerous==0.24
Jinja2==2.7.1
MarkupSafe==0.23
-e git+https://github.com/tejado/pgoapi.git@e8b35057b3c5031f933a19532e81b927a9f12dc0#egg=pgoapi
polyline==1.3.1
protobuf==3.0.0b4
protobuf-to-dict==0.1.0
pycryptodomex==3.4.2
pyproj==1.9.5.1
python-gmaps==0.3.1
pytz==2016.6.1
PyYAML==3.11
requests==2.10.0
s2sphere==0.2.4
six==1.10.0
Werkzeug==0.11.10`

**Comment by IllidanU** [comment]
click==6.6
coverage==4.1
coveralls==1.1
docopt==0.6.2
expiringdict==1.1.3
Flask==0.11.1
Flask-Cors==2.1.2
Flask-GoogleMaps==0.2.0
future==0.15.2
geopy==1.11.0
gpsoauth==0.3.0
itsdangerous==0.24
Jinja2==2.7.1
MarkupSafe==0.23
peewee==2.8.1
protobuf==3.0.0b4
protobuf-to-dict==0.1.0
pycryptodomex==3.4.2
pyproj==1.9.5.1
python-gmaps==0.3.1
pytz==2016.6.1
requests==2.10.0
s2sphere==0.2.4
six==1.10.0
Werkzeug==0.11.10

Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32

**Comment by j-e-k** [comment]
Does changing line 25 in pokemon.py to 
`        self.pokemon_type = pokemon_names.get(str(self.pokemon_id), "NA").encode('utf-8', 'ignore')`

fix the bug?

**Comment by venounan** [comment]
Solved it for me.

**Comment by joychugh** [comment]
ok we'll change that

**Comment by joychugh** [comment]
are you on windows or mac

**Comment by venounan** [comment]
Windows 10

**Comment by IllidanU** [comment]
WIN 10 here 
still exist
2016-07-25 16:11:53,188 [   pokecli] [ERROR] Error in main loop, restarting 'ascii' codec can't encode character u'\u2640' in position 7: ordinal not in range(128)

should I just upgrade to python 3.0?

**Comment by joychugh** [comment]
We can change the name to make sure we don't see the char

**Comment by IllidanU** [comment]
Great! Thanks for you guys so much!
Awesome Bot

**Comment by venounan** [comment]
That would be awesome! Do you guys have any idea why it might have been happening? Just Python nto being able to read the ascii code?

**Comment by joychugh** [comment]
it can be your console most likely works fine on mac

**Comment by joychugh** [comment]
Fixed please check https://github.com/j-e-k/pgoapi/pull/82

**Comment by IllidanU** [comment]
Sorry, I update the code but the error is still here.

2016-07-25 18:45:48,342 [   pokecli] [ERROR] Error in main loop, restarting 'ascii' codec can't encode character u'\u2640' in position 7: ordinal not in range(128)

**Comment by joychugh** [comment]
Damm there must be more pokemon with weird chars,

**Comment by joychugh** [comment]
guys in pokemon.py

make the line looks like this

```
    def __str__(self):
        return unicode("Nickname: {0}, Type: {1}, CP: {2}, IV: {3}".format(self.nickname, self.pokemon_type, self.cp, self.iv))
```

**Comment by IllidanU** [comment]
server down, I will test this asap

**Comment by IllidanU** [comment]
ERROR still here. I tried a different account, it caught a nidoran without any ERROR. But the original account keeps getting error

**Comment by IllidanU** [comment]
More information, running under mac also got this ERROR:

2016-07-25 22:37:31,872 [   pokecli] [ERROR] Error in main loop, restarting 'ascii' codec can't encode character u'\u2640' in position 7: ordinal not in range(128)

**Comment by joychugh** [comment]
Any special char in your account name ? Which country are you from there maybe a locale settings. Try to do unicode("thestringhere") around the log in pgoapi where it prints player information.

**Comment by IllidanU** [comment]
Account name is a combination of uppercase letters and lowercase letters, do not have any other strange chars. Country is Canada. And for the rest part "Try to do unicode("thestringhere") around the log in pgoapi where it prints player information.", I'm not a developer so I do not quite understand what to do. I'm so sorry. But @venounan also encounter this ERROR and I suppose he/she could report the output for this part.
Sorry!

**Comment by IllidanU** [comment]
I FINALLY UNDERSTAND WHY THIS HAPPENED!
I used to add IV numbers to every pokemon I caught. So there exists some Nidoran with special char I renamed. So the program would get an ERROR everytime it try to read my inventory. I removed those special char in the names, everything works fine now.
Thanks for you guys and you can add this to readme: do not add special char to username OR POKEMON NAMES

**Comment by j-e-k** [comment]
Oh wow, gg

**Comment by venounan** [comment]
This could be it for me as well. I added an IV range to my Pokemon's name that had either a "." or a "-" in it. I will remove to test but I won't be able to until tonight. It sounds very possible that that's the solution though.

**Comment by venounan** [comment]
[screenshot_20160726-084812](https://cloud.githubusercontent.com/assets/20630800/17138359/e52a9936-530d-11e6-9a1d-184fe08e2f51.png)

This is how I had then renamed, no special characters after all. I wonder if just adding something to the name that has special characters in it is somehow affecting it.
